### ISSUE TITLE
doesn't work or i can't understand which app token to use

### ISSUE THREAD

**Issue by stefanobrambilla** [TiagoGrosso/instagram-graph-api-lib#240]
hello.
i have a instagram app

i generate a long life token but dosnt work.

invalid oauth access token - cannot parse access token 

can you help me
thanks

**Comment by TiagoGrosso** [comment]
Hi! I'm so sorry, I moved to a new job and kinda neglected side projects while settling in and I missed this message. Do you still have a problem? Can you tell me the steps you took to generate the token?

**Comment by TiagoGrosso** [comment]
Closing this as it seems abandoned. Feel free to comment on this and we'll reopen it
