### ISSUE TITLE
How to publish media ?

### ISSUE THREAD

**Issue by akshatkumawat** [TiagoGrosso/instagram-graph-api-lib#36]
Please add in documentation.
How to publish media on a page.

**Comment by TiagoGrosso** [comment]
Hi! As stated in the README, that feature is not yet supported:

![image](https://user-images.githubusercontent.com/15575832/112728079-5c485580-8f1d-11eb-98e8-ae18a7370038.png)



P.S.: I plan to work on it sometime in the next month

**Comment by akshatkumawat** [comment]
Thank you for your quick response.
Will it work on react native ?

**Comment by TiagoGrosso** [comment]
Hello! Sorry for taking so long to reply, I was finally able to add support for publishing media. I've also added a [new section about it in the README](https://github.com/TiagoGrosso/instagram-graph-api-lib#publishing-media). All you have to do is upgrade to version 1.1.0+

About your question: I've not used this on React Native, only on React websites that I've built, so my guess is "yes, it will work" but I'm not experienced in React Native so I'm not sure if has any limitation about NPM packages that React itself does not have
