### ISSUE TITLE
Does it support close friend adding/removing

### ISSUE THREAD

**Issue by salacoste** [TiagoGrosso/instagram-graph-api-lib#474]
Does it support close friend adding/removing?
if so, can you point me at the place with method name.

**Comment by TiagoGrosso** [comment]
Hi! No, it does not. As far as I'm aware (from https://developers.facebook.com/docs/instagram-platform/reference), the Instagram API itself does not expose anything in regards to friends or close friends, so there's nothing I can do on this project about it until they add support for it on the API
