### ISSUE TITLE
How can we get media info after publishing.

### ISSUE THREAD

**Issue by akshatkumawat** [TiagoGrosso/instagram-graph-api-lib#75]
All we get is 
response like this when post is published.
 {"data": {"id": "18189063760131347"}}
 
 how can we get the details(image id etc ) of the published image/video ?

**Comment by TiagoGrosso** [comment]
Hello! So after you publish the post and get the id, you can do a `GetMediaInfoRequest` to obtain all the data you want for what you just posted

**Comment by akshatkumawat** [comment]
Got it.
Thank you for quick response 🙂
