### ISSUE TITLE
Uploading Reels

### ISSUE THREAD

**Issue by pc11000** [TiagoGrosso/instagram-graph-api-lib#90]
Does this lib support uploading of reels?
Didnt found any information on that. 
And it seems to be a new feature of the instagram-api.

**Comment by TiagoGrosso** [comment]
Hello! It currently does not support that. If the Instagram Graph Api supports it, I can look into it over the next few weeks

**Comment by pc11000** [comment]
Hi, thanks for the quick response.
I think its officially supported since july:
https://developers.facebook.com/blog/post/2022/06/27/introducing-reels-apis-to-instagram-platform/

**Comment by TiagoGrosso** [comment]
Hello! Sorry for the delay. I'll work on it this week

**Comment by TiagoGrosso** [comment]
Release in 5.0.0
